project_id = "nvolvebprvenwzgthfvr"

[functions.notify-unread-messages]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.expire-stale-requests]
verify_jwt = false

[functions.confirm-placement]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
